version: 2

project_name: dockershrink

before:
  hooks:
    - go mod tidy

builds:
  - id: dockershrink
    main: ./main.go
    binary: dockershrink
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/duaraghav8/dockershrink-cli/cmd.version={{.Version}}

checksum:
  name_template: "checksums.txt"

signs:
  - artifacts: checksum

changelog:
  disable: true

brews:
  - url_template: "https://github.com/duaraghav8/dockershrink-cli/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    commit_author:
      name: "Raghav Dua"
      email: "duaraghav8@protonmail.com"
    homepage: "https://dockershrink.com/"
    description: "A commandline tool to reduce the size of Nodejs Docker images"
    dependencies:
      - name: "go"
    repository:
      owner: "duaraghav8"
      name: "homebrew-dockershrink"